# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A random walk Metropolis sampler using Rcpp
#' @description A random walk Metropolis sampler for generating the standard Laplace distribution
#' @param x0 The initial point (double)
#' @param sigma The standard deviation in the normal distribution (double)
#' @param N The length of the chain (int)
#' @return The random numbers and the number of rejections (list)
#' @useDynLib SC19052
#' @import Rcpp
#' @examples
#' \dontrun{
#' N<-1000
#' sigma<-0.05
#' x0<-25
#' rwC(sigma,x0,N)
#' }
#' @export
rwC <- function(sigma, x0, N) {
    .Call('_SC19052_rwC', PACKAGE = 'SC19052', sigma, x0, N)
}

